# pull jdk image from base-repository
FROM openjdk:8-jdk-alpine

# copy run file to repository
copy target/project-0.0.1-SNAPSHOT.jar project-0.0.1-SNAPSHOT.jar

# run java file
ENTRYPOINT ["java", "-jar", "/project-0.0.1-SNAPSHOT.jar"]