server:
  port: 9090

spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: quanph1998@gmail.com
    password: ogdakuavilkvyzaq
    port: 587
    test-connection: false
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          #          ssl:
          #            enable: true
          starttls:
            enable: true