server:
  port: 9081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java_thaycuong_mvc_file
    username: root
    password: root@123


  kafka:
    consumer:
      auto-offset-reset: latest
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      #    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
